// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netinf/android/common/communication/protobuf/TransferringMessage.proto

package netinf.android.common.communication.protobuf;

public final class TransferringMessages {
  private TransferringMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TransferringMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use TransferringMessage.newBuilder() to construct.
    private TransferringMessage() {
      initFields();
    }
    private TransferringMessage(boolean noInit) {}
    
    private static final TransferringMessage defaultInstance;
    public static TransferringMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public TransferringMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netinf.android.common.communication.protobuf.TransferringMessages.internal_static_netinf_android_common_communication_protobuf_TransferringMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netinf.android.common.communication.protobuf.TransferringMessages.internal_static_netinf_android_common_communication_protobuf_TransferringMessage_fieldAccessorTable;
    }
    
    public enum RequestCode
        implements com.google.protobuf.ProtocolMessageEnum {
      REQUEST(0, 100),
      REPLY_OK(1, 200),
      REPLY_ERROR(2, 300),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static RequestCode valueOf(int value) {
        switch (value) {
          case 100: return REQUEST;
          case 200: return REPLY_OK;
          case 300: return REPLY_ERROR;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<RequestCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RequestCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestCode>() {
              public RequestCode findValueByNumber(int number) {
                return RequestCode.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final RequestCode[] VALUES = {
        REQUEST, REPLY_OK, REPLY_ERROR, 
      };
      public static RequestCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private RequestCode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        netinf.android.common.communication.protobuf.TransferringMessages.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:netinf.android.common.communication.protobuf.TransferringMessage.RequestCode)
    }
    
    // required .netinf.android.common.communication.protobuf.TransferringMessage.RequestCode code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.RequestCode code_;
    public boolean hasCode() { return hasCode; }
    public netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.RequestCode getCode() { return code_; }
    
    // required string data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private boolean hasData;
    private java.lang.String data_ = "";
    public boolean hasData() { return hasData; }
    public java.lang.String getData() { return data_; }
    
    private void initFields() {
      code_ = netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.RequestCode.REQUEST;
    }
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasData) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCode()) {
        output.writeEnum(1, getCode().getNumber());
      }
      if (hasData()) {
        output.writeString(2, getData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getCode().getNumber());
      }
      if (hasData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage result;
      
      // Construct using netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage();
        return builder;
      }
      
      protected netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.getDescriptor();
      }
      
      public netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage getDefaultInstanceForType() {
        return netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage) {
          return mergeFrom((netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage other) {
        if (other == netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.RequestCode value = netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.RequestCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setCode(value);
              }
              break;
            }
            case 18: {
              setData(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .netinf.android.common.communication.protobuf.TransferringMessage.RequestCode code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.RequestCode getCode() {
        return result.getCode();
      }
      public Builder setCode(netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.RequestCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.RequestCode.REQUEST;
        return this;
      }
      
      // required string data = 2;
      public boolean hasData() {
        return result.hasData();
      }
      public java.lang.String getData() {
        return result.getData();
      }
      public Builder setData(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = getDefaultInstance().getData();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:netinf.android.common.communication.protobuf.TransferringMessage)
    }
    
    static {
      defaultInstance = new TransferringMessage(true);
      netinf.android.common.communication.protobuf.TransferringMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:netinf.android.common.communication.protobuf.TransferringMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netinf_android_common_communication_protobuf_TransferringMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netinf_android_common_communication_protobuf_TransferringMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nFnetinf/android/common/communication/pr" +
      "otobuf/TransferringMessage.proto\022,netinf" +
      ".android.common.communication.protobuf\"\275" +
      "\001\n\023TransferringMessage\022[\n\004code\030\001 \002(\0162M.n" +
      "etinf.android.common.communication.proto" +
      "buf.TransferringMessage.RequestCode\022\014\n\004d" +
      "ata\030\002 \002(\t\";\n\013RequestCode\022\013\n\007REQUEST\020d\022\r\n" +
      "\010REPLY_OK\020\310\001\022\020\n\013REPLY_ERROR\020\254\002BD\n,netinf" +
      ".android.common.communication.protobufB\024" +
      "TransferringMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_netinf_android_common_communication_protobuf_TransferringMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_netinf_android_common_communication_protobuf_TransferringMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netinf_android_common_communication_protobuf_TransferringMessage_descriptor,
              new java.lang.String[] { "Code", "Data", },
              netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.class,
              netinf.android.common.communication.protobuf.TransferringMessages.TransferringMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
